# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(null=True)),
                ('question_feedback', tinymce.models.HTMLField()),
            ],
        ),
    ]
