# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='question_feedback',
            new_name='questionfeedback',
        ),
    ]
