# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180626_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('dateofbirth', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=40)),
                ('parentgurdianname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(null=True)),
                ('datesubmitted', models.DateTimeField(auto_now_add=True)),
                ('allergiesspecial', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='enroll',
            name='level',
            field=models.ManyToManyField(to='app.level'),
        ),
    ]
