# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180628_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='dateofbirth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
