# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180630_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
