# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=40)),
                ('Surname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='questionfeedback',
            new_name='Question_or_Feedback',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='allergiesspecial',
            new_name='Allergies_or_Special_Needs',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='parentgurdianname',
            new_name='Parent_Gurdian_Name',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='phonenumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='surname',
            new_name='Surname',
        ),
    ]
